(cl:defpackage coax_simple_control-srv
  (:use )
  (:export
   "SETNAVMODE"
   "<SETNAVMODE-REQUEST>"
   "SETNAVMODE-REQUEST"
   "<SETNAVMODE-RESPONSE>"
   "SETNAVMODE-RESPONSE"
   "SETCONTROLMODE"
   "<SETCONTROLMODE-REQUEST>"
   "SETCONTROLMODE-REQUEST"
   "<SETCONTROLMODE-RESPONSE>"
   "SETCONTROLMODE-RESPONSE"
   "SETWAYPOINT"
   "<SETWAYPOINT-REQUEST>"
   "SETWAYPOINT-REQUEST"
   "<SETWAYPOINT-RESPONSE>"
   "SETWAYPOINT-RESPONSE"
  ))

